### ISSUE TITLE
Dockerize. Now!

### ISSUE THREAD

**Issue by portasynthinca3** [Yoyolick/yoyoengine#2]
The genesis of the yoyoengine system dates back a considerable amount of time, indeed, an impressive span of over 11 months. Since its inception, the technological landscape has undergone a myriad of transformations, with one of the most significant being the advent and widespread adoption of Docker. Although zoogies' yoyoengine has proven to be an effective tool, it exhibits notable limitations, particularly in how it does not provide a ready-to-use Docker image.

**Comment by zoogies** [comment]
ok

```Dockerfile
FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    curl \
    zenity \
    git \
    gcc \
    cmake \
    make

RUN git clone https://github.com/zoogies/yoyoengine.git

WORKDIR /yoyoengine/editor

RUN ./build_linux.sh

CMD ["bash"]
```
